import { useCallback, useState } from "react";
import { cn } from "@/lib/utils";

/* ── Country metadata ── */
const COUNTRY_META: Record<string, { flag: string; name: string }> = {
  NGA: { flag: "🇳🇬", name: "Nigeria" },
  GHA: { flag: "🇬🇭", name: "Ghana" },
  KEN: { flag: "🇰🇪", name: "Kenya" },
  ZAF: { flag: "🇿🇦", name: "South Africa" },
  BGD: { flag: "🇧🇩", name: "Bangladesh" },
  IND: { flag: "🇮🇳", name: "India" },
  EGY: { flag: "🇪🇬", name: "Egypt" },
  ETH: { flag: "🇪🇹", name: "Ethiopia" },
  TZA: { flag: "🇹🇿", name: "Tanzania" },
  RWA: { flag: "🇷🇼", name: "Rwanda" },
};

const RISK_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  low: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200" },
  medium: { bg: "bg-amber-50", text: "text-amber-700", border: "border-amber-200" },
  high: { bg: "bg-red-50", text: "text-red-700", border: "border-red-200" },
};

export interface ProfileCardProps {
  isco08: string;
  occupationTitle: string;
  country: string;
  educationLevel: string;
  experienceYears: string;
  informalSkills: string[];
  riskScore: number;
  riskTier: string;
  topPathways: Array<{ title: string; overlapPct: number }>;
}

export function ProfileCard({
  isco08,
  occupationTitle,
  country,
  educationLevel,
  experienceYears,
  informalSkills,
  riskScore,
  riskTier,
  topPathways,
}: ProfileCardProps) {
  const [copied, setCopied] = useState(false);
  const meta = COUNTRY_META[country] ?? { flag: "🌍", name: country };
  const risk = RISK_COLORS[riskTier] ?? RISK_COLORS.medium;
  const riskPct = Math.round(riskScore * 100);

  const handleExport = useCallback(() => {
    const lines = [
      `🌍 UNMAPPED Skills Passport`,
      `━━━━━━━━━━━━━━━━━━━━━━━━`,
      ``,
      `👤 ${occupationTitle} (ISCO-08: ${isco08})`,
      `${meta.flag} ${meta.name}`,
      `📚 Education: ${educationLevel}`,
      `⏱️ Experience: ${experienceYears}`,
      ``,
      `🤖 AI Readiness: ${riskPct}% automation exposure (${riskTier} risk)`,
      ``,
    ];
    if (informalSkills.length > 0) {
      lines.push(`💡 Skills: ${informalSkills.join(", ")}`);
      lines.push(``);
    }
    if (topPathways.length > 0) {
      lines.push(`🔀 Top Transition Pathways:`);
      topPathways.forEach((p, i) => {
        lines.push(`   ${i + 1}. ${p.title} (${Math.round(p.overlapPct)}% skill overlap)`);
      });
      lines.push(``);
    }
    lines.push(`Generated by UNMAPPED — unmapped.app`);

    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [isco08, occupationTitle, country, educationLevel, experienceYears, informalSkills, riskScore, riskTier, riskPct, topPathways, meta]);

  return (
    <div className="relative overflow-hidden rounded-lg border-2 border-ink bg-paper shadow-[6px_6px_0_0_var(--ink)]">
      {/* Subtle country-themed top stripe */}
      <div className="h-2 bg-gradient-to-r from-cobalt via-cobalt/60 to-transparent" />

      <div className="p-5 sm:p-6">
        {/* Header */}
        <div className="flex items-start justify-between gap-3">
          <div>
            <div className="font-mono text-[10px] uppercase tracking-[0.2em] text-muted-foreground">
              Skills Passport
            </div>
            <h3 className="mt-1 font-display text-xl font-black text-ink sm:text-2xl">
              {occupationTitle}
            </h3>
            <p className="font-mono text-xs text-muted-foreground">
              ISCO-08: {isco08}
            </p>
          </div>
          {/* Risk badge */}
          <div
            className={cn(
              "shrink-0 rounded-sm border px-3 py-1.5 text-center",
              risk.bg,
              risk.text,
              risk.border,
            )}
          >
            <div className="font-mono text-lg font-black leading-none">
              {riskPct}%
            </div>
            <div className="mt-0.5 text-[9px] font-semibold uppercase tracking-wider">
              {riskTier} risk
            </div>
          </div>
        </div>

        {/* Country + education + experience */}
        <div className="mt-4 grid grid-cols-3 gap-3 text-xs">
          <div>
            <span className="text-muted-foreground">Country</span>
            <p className="mt-0.5 font-semibold">
              {meta.flag} {meta.name}
            </p>
          </div>
          <div>
            <span className="text-muted-foreground">Education</span>
            <p className="mt-0.5 font-semibold">{educationLevel}</p>
          </div>
          <div>
            <span className="text-muted-foreground">Experience</span>
            <p className="mt-0.5 font-semibold">{experienceYears}</p>
          </div>
        </div>

        {/* Informal skills badges */}
        {informalSkills.length > 0 && (
          <div className="mt-4">
            <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
              Skills
            </span>
            <div className="mt-1.5 flex flex-wrap gap-1.5">
              {informalSkills.map((skill) => (
                <span
                  key={skill}
                  className="rounded-full border border-line bg-muted/50 px-2.5 py-0.5 text-[10px] font-medium text-ink"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Top pathways */}
        {topPathways.length > 0 && (
          <div className="mt-4">
            <span className="text-[10px] font-mono uppercase tracking-wider text-muted-foreground">
              Top Transition Pathways
            </span>
            <div className="mt-1.5 space-y-1.5">
              {topPathways.slice(0, 3).map((pw, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between rounded-sm border border-line px-3 py-2"
                >
                  <span className="text-xs font-medium text-ink">
                    {pw.title}
                  </span>
                  <span className="font-mono text-[10px] font-semibold text-emerald-600">
                    {Math.round(pw.overlapPct)}% overlap
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* QR placeholder + actions */}
        <div className="mt-5 flex items-end justify-between gap-3">
          {/* QR placeholder */}
          <div className="flex h-14 w-14 shrink-0 items-center justify-center rounded border border-line bg-muted/30 text-[10px] font-mono text-muted-foreground">
            QR
          </div>

          {/* Action buttons */}
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleExport}
              className={cn(
                "min-h-[36px] rounded-sm border px-4 py-1.5 font-mono text-[10px] uppercase tracking-wider transition-all",
                copied
                  ? "border-emerald-500 bg-emerald-50 text-emerald-700"
                  : "border-ink bg-ink text-paper hover:bg-ink/90",
              )}
            >
              {copied ? "✓ Copied!" : "Export"}
            </button>
            <button
              type="button"
              onClick={() => {
                /* PDF placeholder — no-op for now */
              }}
              className="min-h-[36px] rounded-sm border border-line px-4 py-1.5 font-mono text-[10px] uppercase tracking-wider text-muted-foreground transition-colors hover:border-ink hover:text-ink"
            >
              Download PDF
            </button>
          </div>
        </div>
      </div>

      {/* Footer branding */}
      <div className="border-t border-line bg-muted/20 px-5 py-2 text-center font-mono text-[9px] uppercase tracking-widest text-muted-foreground">
        Generated by UNMAPPED
      </div>
    </div>
  );
}
