/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReadinessRouteImport } from './routes/readiness'
import { Route as PolicymakerRouteImport } from './routes/policymaker'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as InfrastructureRouteImport } from './routes/infrastructure'
import { Route as EducationRouteImport } from './routes/education'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrosswalkRouteImport } from './routes/crosswalk'
import { Route as CoverageRouteImport } from './routes/coverage'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as IndexRouteImport } from './routes/index'

const InfrastructureRoute = InfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const CrosswalkRoute = CrosswalkRouteImport.update({
  id: '/crosswalk',
  path: '/crosswalk',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverageRoute = CoverageRouteImport.update({
  id: '/coverage',
  path: '/coverage',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadinessRoute = ReadinessRouteImport.update({
  id: '/readiness',
  path: '/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicymakerRoute = PolicymakerRouteImport.update({
  id: '/policymaker',
  path: '/policymaker',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/configure': typeof ConfigureRoute
  '/coverage': typeof CoverageRoute
  '/crosswalk': typeof CrosswalkRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/infrastructure': typeof InfrastructureRoute
  '/passport': typeof PassportRoute
  '/policymaker': typeof PolicymakerRoute
  '/readiness': typeof ReadinessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/configure': typeof ConfigureRoute
  '/coverage': typeof CoverageRoute
  '/crosswalk': typeof CrosswalkRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/infrastructure': typeof InfrastructureRoute
  '/passport': typeof PassportRoute
  '/policymaker': typeof PolicymakerRoute
  '/readiness': typeof ReadinessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/configure': typeof ConfigureRoute
  '/coverage': typeof CoverageRoute
  '/crosswalk': typeof CrosswalkRoute
  '/dashboard': typeof DashboardRoute
  '/education': typeof EducationRoute
  '/infrastructure': typeof InfrastructureRoute
  '/passport': typeof PassportRoute
  '/policymaker': typeof PolicymakerRoute
  '/readiness': typeof ReadinessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/compare' | '/configure' | '/coverage' | '/crosswalk' | '/dashboard' | '/education' | '/infrastructure' | '/passport' | '/policymaker' | '/readiness'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compare' | '/configure' | '/coverage' | '/crosswalk' | '/dashboard' | '/education' | '/infrastructure' | '/passport' | '/policymaker' | '/readiness'
  id:
    | '__root__'
    | '/'
    | '/compare'
    | '/configure'
    | '/coverage'
    | '/crosswalk'
    | '/dashboard'
    | '/education'
    | '/infrastructure'
    | '/passport'
    | '/policymaker'
    | '/readiness'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompareRoute: typeof CompareRoute
  ConfigureRoute: typeof ConfigureRoute
  CoverageRoute: typeof CoverageRoute
  CrosswalkRoute: typeof CrosswalkRoute
  DashboardRoute: typeof DashboardRoute
  EducationRoute: typeof EducationRoute
  InfrastructureRoute: typeof InfrastructureRoute
  PassportRoute: typeof PassportRoute
  PolicymakerRoute: typeof PolicymakerRoute
  ReadinessRoute: typeof ReadinessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/readiness': {
      id: '/readiness'
      path: '/readiness'
      fullPath: '/readiness'
      preLoaderRoute: typeof ReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policymaker': {
      id: '/policymaker'
      path: '/policymaker'
      fullPath: '/policymaker'
      preLoaderRoute: typeof PolicymakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infrastructure': {
      id: '/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof InfrastructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crosswalk': {
      id: '/crosswalk'
      path: '/crosswalk'
      fullPath: '/crosswalk'
      preLoaderRoute: typeof CrosswalkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coverage': {
      id: '/coverage'
      path: '/coverage'
      fullPath: '/coverage'
      preLoaderRoute: typeof CoverageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompareRoute: CompareRoute,
  ConfigureRoute: ConfigureRoute,
  CoverageRoute: CoverageRoute,
  CrosswalkRoute: CrosswalkRoute,
  DashboardRoute: DashboardRoute,
  EducationRoute: EducationRoute,
  InfrastructureRoute: InfrastructureRoute,
  PassportRoute: PassportRoute,
  PolicymakerRoute: PolicymakerRoute,
  ReadinessRoute: ReadinessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
